version: '2'

services:
   db_wordpress:
     image: mariadb:10.6.4-focal
     network_mode: bridge
     hostname: db_wordpress
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     links:
       - db_wordpress
     image: wordpress:latest
     network_mode: bridge
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db_wordpress:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
